### ISSUE TITLE
Tag in GitHub compare link incorrectly prefixed with a 'v'

### ISSUE THREAD

**Issue by SteveVanOpstal** [conventional-changelog-archived-repos/conventional-changelog-core#10]
I recently updated gulp-conventional-changelog from `0.5.1` to `1.1.0`. I use it with the angular preset.

When I update my repository from `1.0.0-alpha.7` to `1.0.0-alpha.8` the 'GitHub compare' link on the title will unnecessarily prefix the most recent tag with a `v`:
https://github.com/SteveVanOpstal/LegendBuilder/compare/1.0.0-alpha.7...v1.0.0-alpha.8

For the link to work, it should be:
https://github.com/SteveVanOpstal/LegendBuilder/compare/1.0.0-alpha.7...1.0.0-alpha.8

It seems like you assume tags are always prefixed with a `v` in [merge-config.js](https://github.com/conventional-changelog/conventional-changelog-core/blob/master/lib/merge-config.js#L259)

**Comment by SteveVanOpstal** [comment]
I already checked if `git log --decorate --no-color` contains the correct tags and it does. So the issue is not in `git-semver-tags`.

**Comment by stevemao** [comment]
Can you provide an easy way to replicate your problem?

**Comment by SteveVanOpstal** [comment]
I forked standard-version and created two tags without the `v`-prefix: https://github.com/SteveVanOpstal/standard-version/releases

When I run `node index.js` standard-version creates this compare link:
https://github.com/conventional-changelog/standard-version/compare/2.2.3...v2.2.2

**Comment by stevemao** [comment]
I tried manually using `git tag` and cannot replicate the issue.
You changed the code in `standard-version` and that might be the problem.

**Comment by stevemao** [comment]
```
<a name="2.0.0"></a>
# [2.0.0](https://github.com/stevemao/test/compare/1.0.0...2.0.0) (2016-05-21)

```

```
git log --decorate
commit 15f9b190e3727c324fa4dab10a831290a4ed1a57 (HEAD -> master, tag: 2.0.0)
Author: Steve Mao <maochenyan@gmail.com>
Date:   Sat May 21 22:47:51 2016 +1000

    feat: haha

commit 3674545fd07ca96172ffa3063105a3f68fb5b1f0 (tag: 1.0.0)
Author: Steve Mao <maochenyan@gmail.com>
Date:   Sat May 21 22:46:06 2016 +1000

    fix: bugs
```

**Comment by stevemao** [comment]
I see what you mean now... `context.currentTag` by default is `'v' + context.version`. You could always change the defaults.

**Comment by stevemao** [comment]
The changelog is generated *before* you tag it. That means it doesn't know what you're gonna tag it. You could tag it as anything basically. It's not recommended to do that.
If you really want to do that and doesn't want to change `context.currentTag` manually, you could generate the changelog *after* you tag it.

**Comment by SteveVanOpstal** [comment]
The main reason why I have non-v-prefixed tags is because I set up my project similarly as the [angular](https://github.com/angular/angular) project. There was also a recent addition to semver that made me lean more to non-v-prefixed tags:
https://github.com/mojombo/semver/blob/master/semver.md#is-v123-a-semantic-version

However, for my convenience and also because I just discovered the pretty awesome standard-version repository, I can drop my autistic ideas and go for v-prefixed tags.

**Comment by stevemao** [comment]
All defaults are meant to be configurable. But using them is highly recommended. Maybe the default `v` should be depending on the previous tag?

**Comment by SteveVanOpstal** [comment]
Seems like a good solution. The only situation that is not covered then is when a repository moves from one prefix type to the another, but this is something that probably won't happen often and it is very easy to fix manually, and only needs to be fixed once. Are there any other situations/prefixes we should consider though?

**Comment by stevemao** [comment]
> Are there any other situations/prefixes we should consider though?

I can't think of any.

**Comment by SteveVanOpstal** [comment]
Me neither

**Comment by stevemao** [comment]
The PR has not been merged yet
