### ISSUE TITLE
wrong default context.linkCompare

### ISSUE THREAD

**Issue by stevemao** [conventional-changelog-archived-repos/conventional-changelog-core#11]
default `context.linkCompare` should also depend on `context.repository` or `context.repoUrl`

**Comment by hutson** [comment]
We're closing this issue out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the issue against the `conventional-changelog` mono-repository.
