### ISSUE TITLE
writer not grouping by type when used with `transform`

### ISSUE THREAD

**Issue by fpereira1** [conventional-changelog-archived-repos/conventional-changelog-core#18]
Hi, great library guys.

I started using this library for my project. While all the commits appear as output, they are not being grouped by type, which is meant to be the default for the writer?

I am running this as: `node changelog.js`

```
var conventionalChangelogCore = require('conventional-changelog-core');

conventionalChangelogCore({
    transform : function(commit, cb) {

      if(/^FIX/.test(commit.header)) {
        commit.type = 'bug';
      }

      if(/^NEW|FEATURE/.test(commit.header)) {
        commit.type = 'feat';
      }

      if(/^bump version --skip-ci/.test(commit.header)) {
        commit = null;
      }

      cb(null, commit);
    },
  })
  .pipe(process.stdout); // or any writable stream

```

**Comment by stevemao** [comment]
You might want to have a look at https://github.com/conventional-changelog/conventional-changelog-writer/issues/20

**Comment by stevemao** [comment]
did you try to config this properly? the writer api will be changed soon.

**Comment by hutson** [comment]
We're closing this issue out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the issue against the `conventional-changelog` mono-repository.
