### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by stevemao** [conventional-changelog-archived-repos/conventional-changelog-core#3]
1. ATM one have to depend on another. This means we can't do `mocha --grep` and only test certain tests so its hard to work with break points. Maybe we could detect if the git history is good before running the `it` block.
2. The construction of git history is partially in `it` blocks. This is fine but the performance tests with `mocha` would count those. Although we don't care about the milliseconds, this could be improved.

Low priority :smile:

**Comment by stevemao** [comment]
Hm... this should be easily done in the `beforeEach` block I think.

**Comment by stevemao** [comment]
opened an issue https://github.com/mochajs/mocha/issues/2191

**Comment by stevemao** [comment]
fixed by aadc6b69ce38af4430dc89e32c4bf62c8f05b19b

**Comment by hutson** [comment]
We're closing this issue out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the issue against the `conventional-changelog` mono-repository.
