### ISSUE TITLE
Mock git to increase test coverage

### ISSUE THREAD

**Issue by stevemao** [conventional-changelog-archived-repos/conventional-changelog-core#9]
https://github.com/conventional-changelog/standard-version/pull/33 :smile:

**Comment by stevemao** [comment]
Use https://github.com/stevemao/mock-git

**Comment by fpereira1** [comment]
@stevemao would this be ok for a first-timer? I looked into the other open issue labeled `help wanted`, but this issue seems like it would most benefit the project. Thanks

**Comment by stevemao** [comment]
@fpereira1 Feel free to send a PR :)

**Comment by hutson** [comment]
We're closing this issue out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the issue against the `conventional-changelog` mono-repository.
